[versions]
# Libraries
activity = "1.11.0"
appcompat = "1.7.1"
compose-bom = "2025.09.00"
compose-coil = "2.7.0"
compose-ui = "1.9.1"
compose-viewmodel = "2.9.3"
coreKtx = "1.17.0"
coroutines-core = "1.10.2"
coroutines-android = "1.10.2"
espressoCore = "3.7.0"
hilt-navigation-compose = "1.3.0"
hilt-work = "1.2.0"
junit = "4.13.2"
junitVersion = "1.3.0"
lifecycle = "2.9.3"
material = "1.13.0"
material3 = "1.3.2"
materialWindowSize = "1.3.2"
navigationCompose = "2.9.4"
okhttp = "5.1.0"
retrofit2Version = "2.11.0"
room = "2.8.0"
tooling-preview = "1.9.1"
moshi = "1.15.1"

# Plugins
agp = "8.13.0"
composePlugin = "2.2.20"
hiltVersion = "2.57.1"
kotlin = "2.2.20"
ksp-version = "2.2.20-2.0.3"
playServicesLocation = "21.3.0"
adsMobileSdk = "0.21.0-beta01"

[libraries]
# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Material Design
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "compose-coil" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "materialWindowSize" }
tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "tooling-preview" }
viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }

# Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-core" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines-android" }

# Lifecycle
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
android-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-navigation-compose" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Retrofit2 and Okhttp
retrofit2-version = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2Version" }
retrofit2-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit2Version" }
okhttp = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
ads-mobile-sdk = { group = "com.google.android.libraries.ads.mobile.sdk", name = "ads-mobile-sdk", version.ref = "adsMobileSdk" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-plugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composePlugin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }

